In [1]:
import numpy as np
import scipy as sp

# LU Decomposition

In LU decomposition, a given matrix A is factored into the product of two matrices: a lower triangular matrix (L) and an upper triangular matrix (U). It is often used for solving systems of linear equations and numerical analysis.

A = LU

In [17]:
A = np.random.randint(0,10,size=(3,3))
A

array([[8, 7, 0],
       [1, 8, 8],
       [4, 8, 4]])

In [18]:
res = sp.linalg.lu(A)

In [19]:
res[0]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
res[1]

array([[1.        , 0.        , 0.        ],
       [0.125     , 1.        , 0.        ],
       [0.5       , 0.63157895, 1.        ]])

In [21]:
res[2]

array([[ 8.        ,  7.        ,  0.        ],
       [ 0.        ,  7.125     ,  8.        ],
       [ 0.        ,  0.        , -1.05263158]])

In [22]:
np.dot(res[1],res[2])

array([[8., 7., 0.],
       [1., 8., 8.],
       [4., 8., 4.]])

# QR Decomposition (QR Factorization)

QR decomposition factorizes a matrix A into the product of an orthogonal matrix (Q) and an upper triangular matrix (R). It is used in various applications, including least squares solutions and eigenvalue calculations.

A = QR

In [24]:
res = sp.linalg.qr(A)

In [25]:
res[0]

array([[-0.88888889,  0.31208735, -0.33537745],
       [-0.11111111, -0.8570757 , -0.50306617],
       [-0.44444444, -0.40990577,  0.79652144]])

In [26]:
res[1]

array([[ -9.        , -10.66666667,  -2.66666667],
       [  0.        ,  -7.95124029,  -8.49622865],
       [  0.        ,   0.        ,  -0.83844362]])

In [27]:
np.dot(res[0],res[1])

array([[ 8.00000000e+00,  7.00000000e+00, -3.44084138e-16],
       [ 1.00000000e+00,  8.00000000e+00,  8.00000000e+00],
       [ 4.00000000e+00,  8.00000000e+00,  4.00000000e+00]])

# Singular Value Decomposition (SVD): 

SVD decomposes a matrix A into three matrices: a left singular vector matrix (U), a diagonal matrix with singular values (Σ), and a right singular vector matrix (V). SVD has numerous applications in data analysis, dimensionality reduction, and image compression.

A = UΣV^T

In [28]:
U,S,VT = sp.linalg.svd(A)

In [29]:
U

array([[-0.53692859,  0.75112833, -0.38407541],
       [-0.60904169, -0.66015279, -0.43962089],
       [-0.58376016, -0.00212709,  0.81192337]])

In [30]:
S

array([16.77113879,  7.51680661,  0.47594341])

In [31]:
VT

array([[-0.43166484, -0.79308358, -0.42974864],
       [ 0.71045669, -0.00536673, -0.70372046],
       [-0.5558028 ,  0.60908918, -0.56576816]])

# Eigenvalue Decomposition

Eigenvalue decomposition decomposes a square matrix A into its eigenvalues (λ) and eigenvectors (V). It is used for diagonalizing matrices and solving differential equations.

A = VΛV^(-1)

In [33]:
V,M = sp.linalg.eig(A)

In [34]:
V

array([16.26994568+0.j,  4.5419858 +0.j, -0.81193147+0.j])

In [35]:
M

array([[-0.52722223, -0.89375672,  0.48932936],
       [-0.62287131,  0.44151763, -0.61599097],
       [-0.57798621, -0.07912719,  0.61734261]])