In [1]:
import numpy as np

<h1> <font size = 15; color = 'tomato'>1. Applications of Matrices and Determinants

## 1.1 Matrices

- Row matrices

In [2]:
A = np.array([1,2,3])

In [3]:
A

array([1, 2, 3])

- coloumn matrices

In [4]:
A = np.ones((3,1))

In [5]:
A

array([[1.],
       [1.],
       [1.]])

- Square matrices

In [7]:
A = np.random.rand(2,2)

In [8]:
A

array([[0.62041954, 0.42004231],
       [0.46397923, 0.94473767]])

In [9]:
A = np.random.rand(3,3)

In [10]:
A

array([[0.85908373, 0.73668952, 0.97405196],
       [0.99999348, 0.21621668, 0.46574237],
       [0.54202594, 0.66299458, 0.9998907 ]])

- Identity Matrices

In [12]:
A = np.identity(3)

In [13]:
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- upper triangular matrices

In [17]:
A = np.zeros((3,3))
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
A[1][0] = 1
A[2][0] = 1
A[2][1] = 1

A

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

- Lower triangular matrices

In [19]:
A = np.zeros((3,3))
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
A[0][1] = 1
A[0][2] = 1
A[1][2] = 1

A

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

- Diagonal matrices

In [22]:
A = np.array([[3,0,0],
              [0,5,0],
              [0,0,7]])

A

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

## 1.2 Determinant of a matrix

The determinant of a square matrix is a scalar value that can be computed from the elements of the matrix. It provides important information about the matrix's properties, including whether the matrix is invertible (non-singular) or singular, and how much the matrix scales the space when used as a linear transformation.

For a square matrix A of size $n \times n$ the determinant is usually denoted as $\vert A \vert$ or $\text{det(A)}$.

In [53]:
A = np.random.rand(2,2)
A

array([[0.3900384 , 0.43638638],
       [0.72176428, 0.90709893]])

In [54]:
 np.linalg.det(A)

0.0388353172391506

In [56]:
A = np.random.randint(0,5,(3,3))

A

array([[1, 3, 1],
       [4, 2, 3],
       [0, 1, 0]])

In [57]:
 np.linalg.det(A)

1.0000000000000004

In [58]:
A = np.random.rand(4,4)

A

array([[0.95045243, 0.95839719, 0.86136212, 0.17431325],
       [0.93948705, 0.77872936, 0.3335935 , 0.96448814],
       [0.24857614, 0.50710294, 0.85311338, 0.65874935],
       [0.25249573, 0.66991961, 0.30506346, 0.84024745]])

In [59]:
 np.linalg.det(A)

-0.27912298517630363

## 1.3 Rank of a matrix

The rank of a matrix *A* is the order of the largest non-zero minor of A and is denoted by $r(A)$. In other words, A positive integer ‘$r$’ is said to be the rank of a non-zero matrix A, if

1. there is atleast one minor of A of order ‘$r$’ which is not zero and
2. every minor of A of order greater than ‘$r$’ is zero.

1. $r(A) \geq 0$
2. If A is a matrix of order $m \times n$ , then $r(A) \leq \text {minimum of {m,n}}$,
3. The rank of a zero matrix is ‘$0$’ 
4. The rank of a non-singular matrix of order $n \times n$ is ‘$n$’

In [43]:
A = np.array([[1,5],
              [3,9]])

A

array([[1, 5],
       [3, 9]])

In [45]:
np.linalg.matrix_rank(A)

2

In [46]:
A = np.random.rand(4,4)
A

array([[0.26292669, 0.92643754, 0.94116585, 0.13970339],
       [0.97580844, 0.2392863 , 0.64429113, 0.29175236],
       [0.94626211, 0.49240124, 0.99446635, 0.16683428],
       [0.13286862, 0.57332387, 0.02186093, 0.59438369]])

In [47]:
np.linalg.matrix_rank(A)

4

In [48]:
A = np.array([[-5, -7],
              [5, 7]])

A

array([[-5, -7],
       [ 5,  7]])

In [49]:
np.linalg.matrix_rank(A)

1

In [51]:
A = np.random.randint(0,10,(2,3))
A

array([[4, 8, 8],
       [4, 3, 3]])

In [52]:
np.linalg.matrix_rank(A)

2

## 1.4 Trigonometrics, Logorithms and exponentials

In [2]:
A = np.random.randn(3,3)

A

array([[-0.3352518 , -1.06991124, -0.84570017],
       [ 0.22527388,  0.59112492, -0.23036776],
       [ 1.57424515,  0.07396279, -0.66973478]])

In [3]:
np.sin(A)

array([[-0.32900696, -0.87715789, -0.74843565],
       [ 0.22337333,  0.55729541, -0.22833558],
       [ 0.99999405,  0.07389538, -0.62077808]])

In [4]:
np.cos(A)

array([[ 0.9443275 ,  0.48020209,  0.66320741],
       [ 0.97473297,  0.83031429,  0.97358249],
       [-0.00344882,  0.997266  ,  0.78398633]])

In [5]:
np.tan(A)

array([[-3.48403455e-01, -1.82664322e+00, -1.12850918e+00],
       [ 2.29163617e-01,  6.71186102e-01, -2.34531314e-01],
       [-2.89952515e+02,  7.40979607e-02, -7.91822583e-01]])

In [6]:
np.sin(A)/np.cos(A)

array([[-3.48403455e-01, -1.82664322e+00, -1.12850918e+00],
       [ 2.29163617e-01,  6.71186102e-01, -2.34531314e-01],
       [-2.89952515e+02,  7.40979607e-02, -7.91822583e-01]])

In [8]:
np.log10(np.abs(A))

array([[-0.47462888,  0.02934775, -0.07278358],
       [-0.64728916, -0.22832073, -0.63757831],
       [ 0.19707237, -1.13098669, -0.17409714]])

In [9]:
np.log2(np.abs(A))

array([[-1.57668302,  0.09749112, -0.24178183],
       [-2.15024804, -0.75846505, -2.11798929],
       [ 0.65466023, -3.75705647, -0.57833819]])

In [11]:
np.log(np.abs(A))

array([[-1.09287339,  0.06757569, -0.16759039],
       [-1.49043837, -0.52572791, -1.46807831],
       [ 0.45377589, -2.6041931 , -0.40087349]])

In [12]:
np.exp(A)

array([[0.71515799, 0.34303896, 0.4292567 ],
       [1.25266575, 1.8060189 , 0.79424146],
       [4.82709653, 1.07676674, 0.51184431]])

In [15]:
A = np.random.randint(0,10,(3,3))
A

array([[3, 9, 0],
       [3, 5, 8],
       [7, 1, 2]])

In [16]:
A**2

array([[ 9, 81,  0],
       [ 9, 25, 64],
       [49,  1,  4]])

In [17]:
A**0.5

array([[1.73205081, 3.        , 0.        ],
       [1.73205081, 2.23606798, 2.82842712],
       [2.64575131, 1.        , 1.41421356]])

In [18]:
A*A

array([[ 9, 81,  0],
       [ 9, 25, 64],
       [49,  1,  4]])

In [20]:
A/A**A

array([[1.11111111e-01, 2.32305731e-08, 0.00000000e+00],
       [1.11111111e-01, 1.60000000e-03, 4.76837158e-07],
       [8.49985975e-06, 1.00000000e+00, 5.00000000e-01]])

In [21]:
A**A

array([[       27, 387420489,         1],
       [       27,      3125,  16777216],
       [   823543,         1,         4]])

## 1.5 Inverse Matrices

In [55]:
A = np.random.randint(1,10, (2,2))

In [56]:
np.linalg.inv(A)

array([[ 0.33333333, -0.11111111],
       [-0.5       ,  0.33333333]])

In [57]:
A = np.random.randint(1,10, (3,3))

In [58]:
np.linalg.inv(A)

array([[ 0.14285714,  0.03571429, -0.10714286],
       [-0.14285714,  0.15178571,  0.04464286],
       [ 0.04761905, -0.1547619 ,  0.13095238]])

## 1.6 Linear Equations

### 1.6.1 Single variable $[ A.X = B ]$ 

If you have a single linear equation with a single variable, you can represent it in matrix form, although it might seem unnecessary for such a simple case. Nevertheless, the representation follows the same principles. Let's say you have the equation:

$A \mathcal X = B$

This can be represented in matrix form as:

$\left[ A \right] \left[ \mathcal X \right] = \left[ B \right] $

which can be solved by:

$\left[ \mathcal X \right] = \left[ B \right] / \left[ A \right] $

In [24]:
A = np.array([10])
B = np.array([5])

In [25]:
B/A

array([0.5])

### 1.6.2 Two variables (Simulteneous equations)

If you have a system of linear equations with two variables, you can represent it in matrix form as well. Let's consider a system of two linear equations:

$$A_{0,0} X + A_{0,1} Y = B_{0,0} \\
A_{1,0} X + A_{1,1} Y = B_{1,0}$$

$$
\begin{align*}
\begin{bmatrix}
A_{0,0} & A_{0,1} \\
A_{1,0} & A_{1,1} \\
\end{bmatrix}
\begin{bmatrix}
X \\
Y \\
\end{bmatrix}
=
\begin{bmatrix}
B_{0,0} \\
B_{1,0} \\
\end{bmatrix}
\end{align*}
$$


In [26]:
A = np.random.randn(2,2)
B = np.random.randint(20,25,(2,1))

In [27]:
A

array([[-0.60941527, -0.1874349 ],
       [ 0.03972641,  0.674203  ]])

In [28]:
B

array([[23],
       [21]])

In [30]:
np.linalg.solve(A,B)

array([[-48.19452154],
       [ 33.98767977]])

### 1.6.3 More than two variables

In [44]:
A = np.random.randint(1,100,(5,5))
B = np.random.randint(2,25,(5,1))

In [45]:
A

array([[ 6, 56, 58, 81, 30],
       [48, 94, 70, 87, 84],
       [18, 54, 26, 79,  4],
       [62, 21,  9, 98, 91],
       [47, 49, 72, 74, 37]])

In [46]:
B

array([[11],
       [ 5],
       [ 9],
       [24],
       [ 8]])

In [47]:
np.linalg.solve(A,B)

array([[-0.06681044],
       [-0.21096538],
       [-0.01741224],
       [ 0.27591582],
       [ 0.06252176]])

In [48]:
A = np.random.randint(1,100,(10,10))
B = np.random.randint(2,25,(10,1))

In [49]:
A

array([[37, 41,  6, 10, 95, 31, 34,  4,  8, 40],
       [93, 81, 54,  7, 41, 55, 59, 50, 24, 64],
       [62, 85, 94,  7, 10, 61, 82,  8, 99, 30],
       [22, 92, 17, 71, 44, 61, 92, 10, 53,  1],
       [62, 76, 43, 20, 80, 33, 88, 50, 49, 57],
       [73, 28, 62, 67,  2, 79, 73,  2, 19, 16],
       [47, 21, 94, 23, 32, 49, 22, 75, 85, 44],
       [47, 89, 15, 58, 53, 59, 72, 79, 61, 13],
       [70, 41, 69, 55, 15, 60,  8, 58, 25, 29],
       [80, 33, 98, 20, 90, 13,  9, 74, 66, 55]])

In [50]:
B

array([[ 6],
       [12],
       [ 7],
       [ 4],
       [ 5],
       [16],
       [15],
       [13],
       [13],
       [24]])

In [52]:
np.linalg.solve(A,B)

array([[  7.68639312],
       [ -2.25244945],
       [-12.13674552],
       [  8.57398625],
       [ -5.11362467],
       [ -4.71431149],
       [ -4.73876124],
       [ -5.99176767],
       [ 11.98297561],
       [ 13.05484101]])