In [1]:
import numpy as np

In [83]:
def cal(x,y,l_1,l_2):
    theta_2 = np.arccos((x**2+y**2-l_1**2-l_2**2)/(2*l_1*l_2))
    theta_1 = (np.arctan(y/x)-(np.arctan((l_2*np.sin(theta_2))/(l_1+(l_2*np.cos(theta_2))))))
    return [theta_1, theta_2, theta_1*180/np.pi, theta_2*180/np.pi]

In [84]:
theta = cal(4,7,7,3)
theta

[0.6759761213144202, 1.4033482475752073, 38.73057880293961, 80.40593177313954]

In [90]:
def mat(theta= [0,0], a = 0,d = 0):
    A_1 = np.array([[np.cos(theta[0]), -1*np.sin(theta[0])*np.cos(theta[1]), np.sin(theta[0])*np.sin(theta[1]), a*np.cos(theta[0])],
                   [np.sin(theta[0]), np.cos(theta[0])*np.cos(theta[1]), -1*np.cos(theta[0])*np.sin(theta[1]), a*np.sin(theta[0])],
                   [0, np.sin(theta[1]), np.cos(theta[1]), d],
                   [0,0,0,1]])
    return A_1

In [93]:
a_1 = mat([cal(4,7,7,3)[0],0], 7)

In [94]:
a_2 = mat([cal(4,7,7,3)[1],0], 3)

In [95]:
np.dot(a_1,a_2)

array([[-0.48689208, -0.87346214,  0.        ,  4.        ],
       [ 0.87346214, -0.48689208,  0.        ,  7.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [31]:
a = np.array([[1,7],[2,4]])
b = np.array([[3,3],[5,2]])

In [36]:
np.dot(a,b)

array([[38, 17],
       [26, 14]])

In [73]:
def rot(a,b):
    if (a[0]):
        R_x = np.array([[1,0,0],
                        [0, np.cos(a[0]), -1*np.sin(a[0])],
                        [0, np.sin(a[0]), np.cos(a[0])]])
        xyz = np.dot(R_x, np.array(b).T)
    elif (a[1]):
        R_y = np.array([[np.cos(a[1]), 0, np.sin(a[1])],
                        [0,1,0],
                        [-np.sin(a[1]), 0, np.cos(a[1])]])
        xyz = np.dot(R_y,np.array(b).T)
    else:
        R_z = np.array([[np.cos(a[2]), -1*np.sin(a[2]), 0],
                        [np.sin(a[2]), np.cos(a[1]), 0],
                        [0,0,1]])
        xyz = np.dot(R_z, np.array(b).T)
    
    return xyz

In [77]:
rot([30*np.pi/180.0, 0, 0],[6,4,2])

array([6.        , 2.46410162, 3.73205081])