<h1><font face='Verdana'; size='20'; color='Navy'><b>NumPy</b></font></h1>

<h2><font face='callibri'; color='salmon'><b>Module / Package</b></font></h2>

In [21]:
import numpy as np

# Operations

In [22]:
np.sqrt(4)

2.0

In [24]:
np.sqrt(3)*np.sqrt(3)

2.9999999999999996

In [25]:
(2*np.sqrt(5))**2

20.000000000000004

In [27]:
(4/(np.sqrt(2)+1))*((np.sqrt(2)-1)/(np.sqrt(2)-1))

1.6568542494923804

In [28]:
(2-np.sqrt(3))**2

0.07179676972449088

In [30]:
3**(-1)+3**(-2)

0.4444444444444444

In [31]:
np.abs(-11)

11

In [32]:
np.abs(11)

11

$|-4-8|$

In [33]:
np.abs(-4-8)

12

# Random Number

In [45]:
np.random.rand(5)

array([0.7381359 , 0.74278619, 0.98498991, 0.49796281, 0.51472704])

In [53]:
np.random.randint(low = 10, high = 20, size = (1,5))

array([[17, 13, 15, 17, 15]])

<h2><font face='callibri'; size='6'; color='mediumblue'><b>1. Arrays</b></font></h2>

In [54]:
np.random.rand(5)

array([0.6799697 , 0.84533056, 0.61544894, 0.89377578, 0.45251083])

In [55]:
np.random.rand(2,2)

array([[0.03092311, 0.25714186],
       [0.31805933, 0.58785401]])

In [56]:
np.random.rand(2,2,2)

array([[[0.142973  , 0.50893366],
        [0.78188493, 0.72310831]],

       [[0.65469024, 0.86465917],
        [0.64714637, 0.36913752]]])

In [57]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [59]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

In [60]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [64]:
a**2

array([ 1,  4,  9, 16, 25])

In [66]:
b = np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [67]:
b+5

array([[ 6,  7,  8],
       [ 8,  9, 10]])

In [68]:
b*2

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [72]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [78]:
np.arange(0,100,10).reshape(5,2)

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [84]:
np.linspace(0,1,10).reshape(2,5)

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

<h2><font face='callibri'; size='6'; color='mediumblue'><b> 2. Vectors </b></font></h2>

In [85]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [87]:
np.random.rand(3,1)

array([[0.73721136],
       [0.24787427],
       [0.14749836]])

In [88]:
np.random.randint(low = 0, high = 5, size= (3,1))

array([[4],
       [1],
       [1]])

In [92]:
a = np.random.randint(low = 0, high = 5, size= (3,1))
b = np.random.randint(low = 8, high = 15, size= (3,1))

In [93]:
a

array([[1],
       [0],
       [3]])

In [94]:
b

array([[10],
       [ 9],
       [ 9]])

In [95]:
a+b

array([[11],
       [ 9],
       [12]])

In [96]:
a-b

array([[-9],
       [-9],
       [-6]])

In [100]:
a*b

array([[10],
       [ 0],
       [27]])

In [101]:
a/b

array([[0.1       ],
       [0.        ],
       [0.33333333]])

In [102]:
sum(a)

array([4])

In [103]:
sum(b)

array([28])

In [104]:
len(a)

3

In [105]:
sum(a)/len(a)

array([1.33333333])

In [106]:
np.mean(a)

1.3333333333333333

In [107]:
min(a)

array([0])

In [108]:
max(b)

array([10])

In [109]:
np.abs(a)

array([[1],
       [0],
       [3]])

In [111]:
np.sqrt(a)

array([[1.        ],
       [0.        ],
       [1.73205081]])

<h2><font face='callibri'; size='6'; color='mediumblue'><b>3. Matrices</b></font></h2>

In [113]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [114]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [115]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
A = np.random.randint(low = 0, high = 20, size = (4,5))
A

array([[13,  9, 18,  0, 12],
       [16,  2,  5, 17,  8],
       [18,  4, 11, 15, 19],
       [ 6, 11, 19, 15, 19]])

In [120]:
A[2][3]

15

In [121]:
A = np.random.randint(low = 0, high = 5, size = (3,3))
B = np.random.randint(low = 10, high = 20, size = (3,3))

In [122]:
A

array([[0, 0, 3],
       [2, 4, 0],
       [2, 2, 0]])

In [123]:
B

array([[15, 14, 11],
       [17, 10, 19],
       [14, 19, 10]])

In [124]:
A+B

array([[15, 14, 14],
       [19, 14, 19],
       [16, 21, 10]])

In [125]:
B-A

array([[15, 14,  8],
       [15,  6, 19],
       [12, 17, 10]])

In [126]:
A*B

array([[ 0,  0, 33],
       [34, 40,  0],
       [28, 38,  0]])

In [127]:
A/B

array([[0.        , 0.        , 0.27272727],
       [0.11764706, 0.4       , 0.        ],
       [0.14285714, 0.10526316, 0.        ]])

In [129]:
np.dot(A,B)

array([[42, 57, 30],
       [98, 68, 98],
       [64, 48, 60]])

In [134]:
A

array([[0, 0, 3],
       [2, 4, 0],
       [2, 2, 0]])

In [130]:
sum(A)

array([4, 6, 3])

In [131]:
len(A)

3

In [133]:
A.size

9

In [135]:
np.mean(A)

1.4444444444444444

In [136]:
np.mean(A, axis = 0) # coloumn mean

array([1.33333333, 2.        , 1.        ])

In [137]:
np.mean(A, axis = 1) # row mean

array([1.        , 2.        , 1.33333333])

In [138]:
B

array([[15, 14, 11],
       [17, 10, 19],
       [14, 19, 10]])

In [139]:
np.transpose(B)

array([[15, 17, 14],
       [14, 10, 19],
       [11, 19, 10]])

In [145]:
a = np.random.rand(3,1)
a

array([[0.82322178],
       [0.09009463],
       [0.30585697]])

In [151]:
a_T = np.transpose(a)
a_T

array([[0.82322178, 0.09009463, 0.30585697]])

In [148]:
B = np.random.randint(0,5,(3,3))
B

array([[3, 4, 2],
       [1, 1, 1],
       [3, 3, 3]])

In [152]:
a*B

array([[2.46966535, 3.29288713, 1.64644356],
       [0.09009463, 0.09009463, 0.09009463],
       [0.9175709 , 0.9175709 , 0.9175709 ]])

In [153]:
a_T*B

array([[2.46966535, 0.36037852, 0.61171394],
       [0.82322178, 0.09009463, 0.30585697],
       [2.46966535, 0.27028389, 0.9175709 ]])

In [154]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [156]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [158]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [159]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [161]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [162]:
np.pi

3.141592653589793

In [168]:
180*np.pi/180

3.141592653589793

In [172]:
np.pi/4*180/np.pi

45.0

In [176]:
np.sin(np.pi)

1.2246467991473532e-16

In [177]:
np.cos(np.pi)

-1.0

In [178]:
np.tan(np.pi)

-1.2246467991473532e-16

In [183]:
np.log(10)

2.302585092994046

In [184]:
np.log2(10)

3.321928094887362

In [185]:
np.log10(10)

1.0