In [1]:
import numpy as np
import sympy as sp

In [2]:
import matplotlib as mat
import mpl_toolkits as mpl
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.gridspec import GridSpecFromSubplotSpec

In [68]:
import tensorflow as tf

In [69]:
# Define matrices A and B
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

In [70]:
A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [71]:
B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>

In [72]:
# Matrix multiplication
tf.matmul(A, B)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [73]:
A+B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float32)>

In [74]:
A-B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4., -4.],
       [-4., -4.]], dtype=float32)>

In [75]:
A*B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5., 12.],
       [21., 32.]], dtype=float32)>

In [76]:
tf.transpose(A)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [2., 4.]], dtype=float32)>

In [77]:
tf.linalg.det(A)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [78]:
tf.linalg.inv(A)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [79]:
tf.linalg.eig(A)

(<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.37228122+0.j,  5.372281  +0.j], dtype=complex64)>,
 <tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
 array([[-0.8245648 +0.j, -0.41597357+0.j],
        [ 0.56576747+0.j, -0.90937674+0.j]], dtype=complex64)>)

In [80]:
tf.linalg.eig(B)

(<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.15206727+0.j, 13.152067  +0.j], dtype=complex64)>,
 <tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
 array([[-0.7586809 +0.j, -0.59276444+0.j],
        [ 0.65146255+0.j, -0.80537593+0.j]], dtype=complex64)>)

In [81]:
tf.linalg.eigvals(A)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.37228122+0.j,  5.372281  +0.j], dtype=complex64)>

In [82]:
tf.linalg.eigvals(B)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.15206727+0.j, 13.152067  +0.j], dtype=complex64)>

In [86]:
tf.linalg.solve(A,tf.constant([[5.],[-8.]]))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-18.000002],
       [ 11.500001]], dtype=float32)>